### ISSUE TITLE
[BUG 🐞] - Imágenes deformadas 

### ISSUE THREAD

**Issue by EduWTR** [nsdonato/recursostech#106]
**Describe el bug**
Las imágenes aparecen un poco distorsionadas ( Producción )
![image](https://github.com/nsdonato/recursostech/assets/139919492/5af109ed-e6d3-4321-9848-5297c78f713f)
![image](https://github.com/nsdonato/recursostech/assets/139919492/4f724962-f208-4aff-99d7-d2ef5dca7965)
![image](https://github.com/nsdonato/recursostech/assets/139919492/c04dd357-611b-4b26-b808-4e39a64b3af0)

**Para reproducir**
Pasos para reproducir el comportamiento:

1. Ir a '...'
2. Haga clic en '....'
3. 3. Desplácese hasta "....
4. Ver error

\*\*Comportamiento esperado
Quitando esta línea funcionan (en figure.tsx ), iba a crear una PR, pero nusé si la aplicaste para otra cosa o planeas usarlo en algo.
 
![image](https://github.com/nsdonato/recursostech/assets/139919492/2e7ce5c4-acd1-4b14-9dc5-5dbd6ead130e)

**Capturas de pantalla**

en localhost:
![image](https://github.com/nsdonato/recursostech/assets/139919492/47134abf-6528-446c-b3f0-e821b034923f)
![image](https://github.com/nsdonato/recursostech/assets/139919492/5158d6fa-6b4e-424e-b47f-3a10993e6b27)

**Escritorio (complete la siguiente información):**

- SISTEMA OPERATIVO: Linux
- Navegador: Brave
- Versión [ej. 22]

**Smartphone (por favor, complete la siguiente información):**

- Dispositivo: [p. ej. iPhone6]
- SISTEMA OPERATIVO: [p. ej. iOS8.1]
- Navegador [p.ej. stock browser, safari]
- Versión [por ejemplo, 22]

\*\*Contexto adicional
Añade aquí cualquier otro contexto sobre el problema.

**Comment by nsdonato** [comment]
Mala mia, quise arreglar un tema de consola, vi esto y cuando lo iba a arreglar me tuve que ir. En breve lo arreglo, me lo asigno! Gracias por levantarlo <3

**Comment by nsdonato** [comment]
Ya lo arreglé, si llegará a haber alguna otra imagen me avisas? Gracias <3
