### ISSUE TITLE
[BUG TYPO 🐞 INICIO] - Ausencia de un signo de interrogación y error de tipeo.

### ISSUE THREAD

**Issue by jjmajori** [nsdonato/recursostech#124]
**Describe el bug**

En el texto de del inicio se puede observar:
Ausencia del signo de interrogación en el comienzo de la 5ta línea.
Error de tipeo en la palabra RECURSO de la 8va línea.

![typo recursosdev](https://github.com/nsdonato/recursostech/assets/159586163/4fc7baf5-7441-4cb7-8a7e-bec44ff55c77)

- SISTEMA OPERATIVO: [Sonoma 14.3.1]
- Navegador [Chrome]
- Versión [123.0.6312.105]

**Comment by nsdonato** [comment]
Ups! Bien atrapado 😊 si no soy yo, alguna persona que quiera aportar lo corregirá a la brevedad, muchas gracias!

**Comment by nsdonato** [comment]
Closes to https://github.com/nsdonato/recursostech/pull/127
