### ISSUE TITLE
[BUG 🐞 INICIO] - Iconos de redes sociales con diferentes tamaños.

### ISSUE THREAD

**Issue by jjmajori** [nsdonato/recursostech#125]
**Describe el bug**

Se puede visualizar que los iconos de las redes sociales poseen 3 tamaños diferentes.

Discord 40x40
Twitter 35x35
El resto 30X30

![typo recursosdev](https://github.com/nsdonato/recursostech/assets/159586163/e00d2a69-f7da-451f-8bab-50ca7d9ad43c)

- SISTEMA OPERATIVO: [Sonoma 14.3.1]
- Navegador [Chrome]
- Versión [123.0.6312.105

**Comment by EduWTR** [comment]
Originalmente los logos eran monocromáticos, pero faltaban algunos , fuí agarrando de diferentes sitios.

Quizás para volver a la idea original de Noe, estuve buscando logos.

![image](https://github.com/nsdonato/recursostech/assets/139919492/726febbf-9691-4e96-8c4a-f3f91321022a)

Que les parecen estos? de : https://simpleicons.org/

**Comment by jjmajori** [comment]
> Originalmente los logos eran monocromáticos, pero faltaban algunos , fuí agarrando de diferentes sitios.
> 
> Quizás para volver a la idea original de Noe, estuve buscando logos.
> 
> ![image](https://private-user-images.githubusercontent.com/139919492/320076724-726febbf-9691-4e96-8c4a-f3f91321022a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNDQ1MzYsIm5iZiI6MTcxMjM0NDIzNiwicGF0aCI6Ii8xMzk5MTk0OTIvMzIwMDc2NzI0LTcyNmZlYmJmLTk2OTEtNGU5Ni04YzRhLWYzZjkxMzIxMDIyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxOTEwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzI1MTQyM2U1MDA0Y2ZhMzJjMDgwNmRlZDI5NDFhMWMwNWQ3NmFhNDU3NmQ5MGNkYzEzMTkzNWMwYTU1ZWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7wqbFpUotHWo9DUtoIfaOHpD1j2j3B8qQ7JrqVTd7g0)
> 
> Que les parecen estos? de : https://simpleicons.org/

Me parece buena idea volver a los monocromáticos. Creo que quedaría mejor a nivel contraste en los diferentes mode Dark / Light. 
Lo importante que es todos mantengan el misma tamaño.

**Comment by nsdonato** [comment]
Closes to #127
