### ISSUE TITLE
EPICA [💅🏼 Mejora] - Actualización de SVG's

### ISSUE THREAD

**Issue by nsdonato** [nsdonato/recursostech#25]
Esta tarea es una epica y voy a ir agregando mini subtareas para realizar como good first issue, es un aporte visual a la página:

- [x] #26
- [x] #27
- [x] #28

**Comment by IvanMJs** [comment]
Agregue un PR con la actualización de los iconos en **SVG y Negros**, no estoy seguro si cubre todas las subtareas o solo alguna:

[PR Update SVG's icons](https://github.com/nsdonato/recursostech/pull/34)

**Comment by nsdonato** [comment]
> Agregue un PR con la actualización de los iconos en **SVG y Negros**, no estoy seguro si cubre todas las subtareas o solo alguna:
> 
> [PR Update SVG's icons](https://github.com/nsdonato/recursostech/pull/34)

Cubre la 2da y 3er tarea, gracias!

**Comment by isahecam** [comment]
Hola! He realizado una PR sobre la actualización de la 3ra y 4ta tanda de iconos.
