### ISSUE TITLE
[NEW 🆕] - Agregar recurso

### ISSUE THREAD

**Issue by alanrios21** [nsdonato/recursostech#40]
**Por favor escribí la información necesaria del recurso para poder sumarla:**

Links:

Twitch: (https://www.twitch.tv/mouredev)
IG: (https://www.instagram.com/mouredev)
YouTube: (https://www.youtube.com/@mouredev)
Discord: (https://discord.com/invite/mouredev)
Twitter: (https://twitter.com/MoureDev)
Web: (https://mouredev.com/)

Svg del recurso (opcional pero ideal):

- subir el svg al issue

Video (opcional):

- 🚨 Por el momento solo videos en español. Link al video de la persona explicando sobre el recurso, ej si es una extensión, como se usa.

**De ser necesario, sumar contexto adicional**
Tecnologías: Python, SQL

**Comment by alanrios21** [comment]
Este recurso iria en la seccion de Streamers Backend

**Comment by nsdonato** [comment]
> Este recurso iria en la seccion de Streamers Backend

Yo diría de agregarlo en mobile, que al parecer es su fuerte. Como nota para quien tome este pedido.

**Comment by mariaelisaaraya** [comment]
Hola! Tomo este issue.

**Comment by mariaelisaaraya** [comment]
Este realizado:  https://www.recursostech.dev/docs/mobile/streamers

**Comment by nsdonato** [comment]
Lo cierro, gracias por avisar @mariaelisaaraya
