### ISSUE TITLE
[NEW 🆕] - Agregar recurso de animaciones

### ISSUE THREAD

**Issue by samuelgomez4** [nsdonato/recursostech#57]
Recursos de animaciones para la web

Links:
https://animate.style/
https://animista.net/
https://sarthology.github.io/Animatopy/
https://www.cattocss.com/
https://ianlunn.github.io/Hover/
https://xsgames.co/animatiss/
https://michalsnik.github.io/aos/
https://www.tailwindcss-animated.com/
https://gsap.com/
https://auto-animate.formkit.com/
https://www.react-magic-motion.com/applications/collapsible-sidebar
https://rive.app/
https://www.framer.com/motion/
https://motion.dev/

**Comment by mariaelisaaraya** [comment]
Hola Noe! Tomo el issue.
Consulta:
¿Agrego una sección nueva en frontend llamada "Animaciones" o lo sumo en la seccion Frontend/Imagenes? Otra puede ser cambiar el nombre de Imagenes por "Imagenes/Animaciones"

**Comment by nsdonato** [comment]
Diría de crear una de animaciones, gracias 🙌🏻♥️

**Comment by nsdonato** [comment]
Closes #90
