### ISSUE TITLE
[NEW 🆕] - Agregar recurso Pythonanywhere

### ISSUE THREAD

**Issue by smenendez19** [nsdonato/recursostech#58]
**Por favor escribí la información necesaria del recurso para poder sumarla:**
Pagina para poder deployear codigo realizado principalmente con Python, con espacio en la nube, schedule y posibilidad de dominio personalizado.
Esta más enfocado en deploy de codigo Backend.

Links (opcional pero ideal):
- <https://www.pythonanywhere.com/>

Svg del recurso:
![PA-logo-snake-only](https://github.com/nsdonato/recursostech/assets/42306463/cc4a9fb2-d6e6-4883-8005-22d29b9017b5)

Añade aquí cualquier otro contexto o capturas de pantalla sobre la solicitud de función:

Tecnologias: Python, Jupyter Notebook

(Captura de ejemplo de dashboard con mi usuario)
![image](https://github.com/nsdonato/recursostech/assets/42306463/b04af223-66b8-4dd1-b0bf-a5f1663acf08)

**Comment by mariaelisaaraya** [comment]
Hola Noe! Agarro este = )

**Comment by nsdonato** [comment]
Closes at #101 

Gracias @mariaelisaaraya
