### ISSUE TITLE
[NEW 🆕] - Agregar recurso

### ISSUE THREAD

**Issue by alanrios21** [nsdonato/recursostech#6]
**Por favor escribí la información necesaria del recurso para poder sumarla:**

Links:

(https://pages.github.com/)

Svg del recurso (opcional pero ideal):

![iconmonstr-github-1](https://github.com/nsdonato/recursostech/assets/58795417/a13d41b5-812c-4d28-aea2-be94fb9ab831)

Video (opcional):

[https://www.youtube.com/shorts/qprqCT9qjgo](url)

**De ser necesario, sumar contexto adicional**
Añade aquí cualquier otro contexto o capturas de pantalla sobre la solicitud de función.

**Comment by nsdonato** [comment]
En breve se sube mediante este PR, gracias! #10

**Comment by nsdonato** [comment]
Se cierra el Issue ya que se mergeó el PR ✨
